feat: add dashboard port increment
deggja/netfetch pull request #36
Opened 2023-12-10 11:15 UTC by Slartibartfast1

Added function to find the next available port when running the dashboard. It'll start at 8080 and increment up by 1 until an unused port is found.

Proposed as a solution to #8.

![image](https://github.com/deggja/netfetch/assets/25581895/30e8d298-d9d6-43c9-ba49-9dbccfe21ca1)

2023-12-10 13:54 UTC, deggja requested changes
Hello @Slartibartfast1!

Thanks a lot for checking out the application and making a PR! I like how you just picked up one of the available issues, thats amazing and I hope you will continue contributing going forward 🚀

I added some comments to your pull request. Could you have a look at them when you get the time?

2023-12-10 13:54 UTC, deggja commented on backend/cmd/dash.go
> +	port := getNextAvailablePort("8080")
I believe you will get issues here. CORS is configured to handle requests from 8080 and 8081. Once you reach 8082 it will no longer work with this code.
We are using statik to bundle the frontend and backend together, however the frontend will still be expecting the requests to come from 8080 or 8081.

So I believe we need to implement the two following things:

1. CORS must dynamically allow the dynamically assigned available port. 
2. The frontend must dynamically construct the URL based on what port the connection was established on for the backend.

2023-12-10 13:54 UTC, deggja commented on backend/cmd/dash.go
> +func getNextAvailablePort(startPort string) string {
This func looks good. Can you include error handling here as well? In case of error happening when converting port from string to integer.

2023-12-10 13:54 UTC, deggja commented on backend/cmd/dash.go
> +            port = strconv.Itoa(int + 1)
We should make sure that no infinite loop happens. Right now it will continue +1 until it finds an available port, but maybe in some rare scenario it never will and the dashboard wont start. We should add some sort of limit to how many attempts the application can make to find an available port.

2023-12-10 19:19 UTC, Slartibartfast1 commented on backend/cmd/dash.go
> +            port = strconv.Itoa(int + 1)
Added a limit to the loop. I'm now wondering if 10 is too low though?

2023-12-10 19:20 UTC, Slartibartfast1 commented on backend/cmd/dash.go
> +func getNextAvailablePort(startPort string) string {
Added a log.Fatalf() as used further up the same file to handle an error here.

2023-12-10 19:34 UTC, Slartibartfast1 commented
No problem. I though instead of hard-coding "8081" just for myself that I could maybe tackle the issue and practice some Go.

Vue and JavaScript are well outside my wheelhouse - but I like a challenge :smile:.

2023-12-10 20:04 UTC, deggja commented on backend/cmd/dash.go
> +            port = strconv.Itoa(int + 1)
Nice. 10 is fine for now. We can always change it later if we see any corner cases where ten for some reason is not enough.

2023-12-10 20:05 UTC, deggja commented
> No problem. I thought instead of hard-coding "8081" just for myself that I could maybe tackle the issue and practice some Go.
> 
> Vue and JavaScript are well outside my wheelhouse - but I like a challenge 😄.

Glad you're up for the challenge 🤝 
Looking forward to see what you come up with!

2023-12-13 07:16 UTC, Slartibartfast1 commented
So, if I understand this correctly... the port variable needs to be baked into App.vue before being served by the backend. This needs to be done with Statik as the file structure is already embedded into a binary.

This is what I was thinking of doing, but no matter what I give to fs.ReadFile() it never finds App.vue.

```
func dashboardHandler(w http.ResponseWriter, r *http.Request) {
	statikFS, err := fs.New()
	if err != nil {
		log.Fatal(err)
	}

        htmlContent, err := fs.ReadFile(statikFS, "/dash/src/App.vue")

        tmpl, err := template.New("dashboard").Parse(string(htmlContent))

        portMap := map[string]string{"port": port}

        err = tmpl.Execute(w, portMap)

	// Serve the embedded frontend
	http.FileServer(statikFS).ServeHTTP(w, r)
}
```

Maybe I just haven't understood the root directory in `statikFS`, or I might be going down the wrong path completely :smile:. What are your thoughts @deggja?

2023-12-13 18:40 UTC, deggja commented
> So, if I understand this correctly... the port variable needs to be baked into App.vue before being served by the backend. This needs to be done with Statik as the file structure is already embedded into a binary.
> 
> This is what I was thinking of doing, but no matter what I give to fs.ReadFile() it never finds App.vue.
> 
> ```
> func dashboardHandler(w http.ResponseWriter, r *http.Request) {
> 	statikFS, err := fs.New()
> 	if err != nil {
> 		log.Fatal(err)
> 	}
> 
>         htmlContent, err := fs.ReadFile(statikFS, "/dash/src/App.vue")
> 
>         tmpl, err := template.New("dashboard").Parse(string(htmlContent))
> 
>         portMap := map[string]string{"port": port}
> 
>         err = tmpl.Execute(w, portMap)
> 
> 	// Serve the embedded frontend
> 	http.FileServer(statikFS).ServeHTTP(w, r)
> }
> ```
> 
> Maybe I just haven't understood the root directory in `statikFS`, or I might be going down the wrong path completely 😄. What are your thoughts @deggja?

I think that approach might work with _normal_ static js files, but using statik.go the files are bundled within the go binary itself. So I'm not sure about that approach.

I made a branch where I implemented a solution you can take a look at here: https://github.com/deggja/netfetch/tree/feat_8

I reduced the number of checks to 5 because 10 felt slow. Feel free to share your thoughts on this approach. 

Also, your general thoughts on doing this in the first place. Do we want to dynamically set the port - or should we simply tell the user to clean up whatever is using the port before re-running the application instead?

2023-12-13 20:33 UTC, Slartibartfast1 commented
Ah, I like it.

I think having it dynamic is the best option. More flexible, less intrusive to the user - there are just so many applications using 8080, Netfetch might lose the priority fight on that one. It'd probably be better to pick a new one to stick with static.

2023-12-13 20:43 UTC, deggja commented
> Ah, I like it.
> 
> 
> 
> I think having it dynamic is the best option. More flexible, less intrusive to the user - there are just so many applications using 8080, Netfetch might lose the priority fight on that one. It'd probably be better to pick a new one to stick with static.

Cool. I agree with you. Lets go for the dynamic port. Wanna update your PR with the changes? Feel free to double check that it works and implement the changes you feel like it needs.

2024-01-15 20:56 UTC, deggja commented
Closing PR. No response from submitter.

2024-01-15 20:56 UTC, closed without merging